apiVersion: batch/v1
kind: CronJob
metadata:
  name: processor-batch-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: processor-batch
            image: stakkato95/lambda-processor-batch
          restartPolicy: OnFailure